# Generated by Django 4.2.2 on 2023-06-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Patient',
        ),
    ]
